server:
  port: 8001
spring:
  application:
    name: api-service


eureka:
  client:
    service-url:
      defaultZone: http://lin:www.daizening.com@127.0.0.1:8888/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true